//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Despegar.LegacyCore.Connector {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class APIConnector_keys {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal APIConnector_keys() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Despegar.LegacyCore.Connector.APIConnector.keys", typeof(APIConnector_keys).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dcb50a69-d4bc-4bc8-af64-97456a16964f.
        /// </summary>
        internal static string _default_ {
            get {
                return ResourceManager.GetString("_default_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a8c78c20-fc07-4283-9278-c436e57610bf.
        /// </summary>
        internal static string AR {
            get {
                return ResourceManager.GetString("AR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99a09314-7fc4-465a-9ea8-cedb64bd3571.
        /// </summary>
        internal static string AU {
            get {
                return ResourceManager.GetString("AU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16307f0b-cee5-4128-9a85-51c08e4b3fff.
        /// </summary>
        internal static string BO {
            get {
                return ResourceManager.GetString("BO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to b5e22dd1-bc47-48ed-bb8d-d9584865eb09.
        /// </summary>
        internal static string BR {
            get {
                return ResourceManager.GetString("BR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d40a1d5e-418d-4961-9297-f0e8e2ab89f4.
        /// </summary>
        internal static string CL {
            get {
                return ResourceManager.GetString("CL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to af42b886-69d2-4bd0-a120-bba62830ea73.
        /// </summary>
        internal static string CO {
            get {
                return ResourceManager.GetString("CO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2fb184bc-e0ca-44dd-bab2-3dac5d5a3a97.
        /// </summary>
        internal static string CR {
            get {
                return ResourceManager.GetString("CR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ef647bad-22fc-444a-9869-c54013d270b0.
        /// </summary>
        internal static string DO {
            get {
                return ResourceManager.GetString("DO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 96b16217-bfff-4a9b-a2ec-4b1660a83a84.
        /// </summary>
        internal static string EC {
            get {
                return ResourceManager.GetString("EC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bbdbfda0-fb1e-436a-a4c7-eddd8a968e04.
        /// </summary>
        internal static string ES {
            get {
                return ResourceManager.GetString("ES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d0c90c00-0cb8-46f7-bef0-443ea589b2e6.
        /// </summary>
        internal static string GT {
            get {
                return ResourceManager.GetString("GT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to f4534312-9b3b-4040-88f1-5e652d841233.
        /// </summary>
        internal static string HN {
            get {
                return ResourceManager.GetString("HN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aa34efc7-a990-4324-8526-d67b56f1bc3e.
        /// </summary>
        internal static string MX {
            get {
                return ResourceManager.GetString("MX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8df7b8d4-dc96-446c-b73b-e7caa46dfe6d.
        /// </summary>
        internal static string NI {
            get {
                return ResourceManager.GetString("NI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 011c0601-04eb-42c4-b9a7-b790d4d9f912.
        /// </summary>
        internal static string PA {
            get {
                return ResourceManager.GetString("PA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5ba7828e-7057-413c-b16a-4b750ec66c6d.
        /// </summary>
        internal static string PE {
            get {
                return ResourceManager.GetString("PE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 32b294b6-455e-4a55-a43d-1f2b9a7d6c74.
        /// </summary>
        internal static string PR {
            get {
                return ResourceManager.GetString("PR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5f9a3bf1-4e92-42f7-8ad6-5ba93903633d.
        /// </summary>
        internal static string PY {
            get {
                return ResourceManager.GetString("PY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1620dadc-b0b2-4cdc-9d20-9ce101e8d89c.
        /// </summary>
        internal static string SV {
            get {
                return ResourceManager.GetString("SV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4dfa1713-5f67-4ad6-88ae-1dd24124264a.
        /// </summary>
        internal static string US {
            get {
                return ResourceManager.GetString("US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to f3fd9c45-4e1b-498b-9c51-1be980940e31.
        /// </summary>
        internal static string UY {
            get {
                return ResourceManager.GetString("UY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 869e3495-a303-497f-9aa9-e05690815d6a.
        /// </summary>
        internal static string VE {
            get {
                return ResourceManager.GetString("VE", resourceCulture);
            }
        }
    }
}
