//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Despegar.LegacyCore.Connector {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Connector_url {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Connector_url() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Despegar.LegacyCore.Connector.Connector.url", typeof(Connector_url).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api.despegar.com.
        /// </summary>
        internal static string _base_api {
            get {
                return ResourceManager.GetString("_base_api", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api.despegar.it.
        /// </summary>
        internal static string _base_api_rc {
            get {
                return ResourceManager.GetString("_base_api_rc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mobile.despegar.com.
        /// </summary>
        internal static string _base_mapi {
            get {
                return ResourceManager.GetString("_base_mapi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mobile.despegar.it.
        /// </summary>
        internal static string _base_mapi_rc {
            get {
                return ResourceManager.GetString("_base_mapi_rc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m.despegar.com.ar.
        /// </summary>
        internal static string _base_mobile {
            get {
                return ResourceManager.GetString("_base_mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to upa.despegar.com.
        /// </summary>
        internal static string _base_upa {
            get {
                return ResourceManager.GetString("_base_upa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://.
        /// </summary>
        internal static string _http {
            get {
                return ResourceManager.GetString("_http", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://.
        /// </summary>
        internal static string _https {
            get {
                return ResourceManager.GetString("_https", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /beta.
        /// </summary>
        internal static string _version_beta {
            get {
                return ResourceManager.GetString("_version_beta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string _version_none {
            get {
                return ResourceManager.GetString("_version_none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v1.
        /// </summary>
        internal static string _version_v1 {
            get {
                return ResourceManager.GetString("_version_v1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v3.
        /// </summary>
        internal static string _version_v3 {
            get {
                return ResourceManager.GetString("_version_v3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /configuration.
        /// </summary>
        internal static string api_configuration {
            get {
                return ResourceManager.GetString("api_configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /availability/flights/reprice/{0}/{1}?fullretrive=true.
        /// </summary>
        internal static string api_flights_availability_reprice {
            get {
                return ResourceManager.GetString("api_flights_availability_reprice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /booking/flights/book.
        /// </summary>
        internal static string api_flights_booking_book {
            get {
                return ResourceManager.GetString("api_flights_booking_book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /booking/flights/fields/{0}/{1}?{2}&amp;devicedescription={3}.
        /// </summary>
        internal static string api_flights_booking_fields {
            get {
                return ResourceManager.GetString("api_flights_booking_fields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /countries?pagesize=250.
        /// </summary>
        internal static string api_geo_countries {
            get {
                return ResourceManager.GetString("api_geo_countries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /countries/{0}.
        /// </summary>
        internal static string api_geo_country {
            get {
                return ResourceManager.GetString("api_geo_country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /availability/hotels/{0}/booking?checkin={1}&amp;checkout={2}&amp;distribution={3}&amp;includehotel={4}&amp;discount={5}&amp;discountcurrency={6}&amp;roomsdetail=true.
        /// </summary>
        internal static string api_hotels_availability_booking {
            get {
                return ResourceManager.GetString("api_hotels_availability_booking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /booking/hotels/{0}/{1}/book.
        /// </summary>
        internal static string api_hotels_booking_book {
            get {
                return ResourceManager.GetString("api_hotels_booking_book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /booking/hotels/fields/{0}?{1}&amp;devicedescription={2}.
        /// </summary>
        internal static string api_hotels_booking_fields {
            get {
                return ResourceManager.GetString("api_hotels_booking_fields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /currencies?pagesize=200.
        /// </summary>
        internal static string api_misc_currencies {
            get {
                return ResourceManager.GetString("api_misc_currencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /countries/{0}/states.
        /// </summary>
        internal static string api_states {
            get {
                return ResourceManager.GetString("api_states", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /booking/validation/creditcards.
        /// </summary>
        internal static string api_validation_creditcards {
            get {
                return ResourceManager.GetString("api_validation_creditcards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /mapi-cross/autocomplete/{0}/{1}?administrative_division_id={2}&amp;city_result=5.
        /// </summary>
        internal static string mapi_cities {
            get {
                return ResourceManager.GetString("mapi_cities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /push-service/data/register.
        /// </summary>
        internal static string mapi_dpns_register {
            get {
                return ResourceManager.GetString("mapi_dpns_register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /push-service/data/register/booking.
        /// </summary>
        internal static string mapi_dpns_register_booking {
            get {
                return ResourceManager.GetString("mapi_dpns_register_booking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /mobile-css-versioned/wp/discounts/wp8.json?_t={0}.
        /// </summary>
        internal static string mobile_discounts {
            get {
                return ResourceManager.GetString("mobile_discounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /mobile-css-versioned/wp/configuration?_t={0}.
        /// </summary>
        internal static string mobile_remote_configuration {
            get {
                return ResourceManager.GetString("mobile_remote_configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /t.
        /// </summary>
        internal static string upa_get_id {
            get {
                return ResourceManager.GetString("upa_get_id", resourceCulture);
            }
        }
    }
}
