//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Despegar.LegacyCore.Resource {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Properties {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Properties() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Despegar.LegacyCore.Resource.Properties", typeof(Properties).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prôximo.
        /// </summary>
        internal static string AppBarNextField {
            get {
                return ResourceManager.GetString("AppBarNextField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anterior.
        /// </summary>
        internal static string AppBarPreviousField {
            get {
                return ResourceManager.GetString("AppBarPreviousField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conexão com espera de.
        /// </summary>
        internal static string CheckoutLabel_Details_ConectionWith {
            get {
                return ResourceManager.GetString("CheckoutLabel_Details_ConectionWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vôo.
        /// </summary>
        internal static string CheckoutLabel_Details_Flight {
            get {
                return ResourceManager.GetString("CheckoutLabel_Details_Flight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desde.
        /// </summary>
        internal static string CheckoutLabel_Details_From {
            get {
                return ResourceManager.GetString("CheckoutLabel_Details_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IDA.
        /// </summary>
        internal static string CheckoutLabel_Details_IDA {
            get {
                return ResourceManager.GetString("CheckoutLabel_Details_IDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  noite(s).
        /// </summary>
        internal static string CheckoutLabel_Details_Nights {
            get {
                return ResourceManager.GetString("CheckoutLabel_Details_Nights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quarto(s).
        /// </summary>
        internal static string CheckoutLabel_Details_Rooms {
            get {
                return ResourceManager.GetString("CheckoutLabel_Details_Rooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trecho.
        /// </summary>
        internal static string CheckoutLabel_Details_Segment {
            get {
                return ResourceManager.GetString("CheckoutLabel_Details_Segment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to para.
        /// </summary>
        internal static string CheckoutLabel_Details_To {
            get {
                return ResourceManager.GetString("CheckoutLabel_Details_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duração total de vôo:.
        /// </summary>
        internal static string CheckoutLabel_Details_TotalTime {
            get {
                return ResourceManager.GetString("CheckoutLabel_Details_TotalTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VOLTA.
        /// </summary>
        internal static string CheckoutLabel_Details_VUELTA {
            get {
                return ResourceManager.GetString("CheckoutLabel_Details_VUELTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, ingrese el código de área del teléfono..
        /// </summary>
        internal static string CheckoutLabel_Error_areaCode_INVALID_LENGTH {
            get {
                return ResourceManager.GetString("CheckoutLabel_Error_areaCode_INVALID_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, verifique que el código de área sólo contenga números..
        /// </summary>
        internal static string CheckoutLabel_Error_areaCode_INVALID_PHONE_AREA_CODE {
            get {
                return ResourceManager.GetString("CheckoutLabel_Error_areaCode_INVALID_PHONE_AREA_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, preencha o número de cartão..
        /// </summary>
        internal static string CheckoutLabel_Error_cardNumber_INVALID_LENGTH {
            get {
                return ResourceManager.GetString("CheckoutLabel_Error_cardNumber_INVALID_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, preencha o código do país do telefone..
        /// </summary>
        internal static string CheckoutLabel_Error_countryCode_INVALID_LENGTH {
            get {
                return ResourceManager.GetString("CheckoutLabel_Error_countryCode_INVALID_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, verifique o código do país só seja números..
        /// </summary>
        internal static string CheckoutLabel_Error_countryCode_NOT_NUMERIC {
            get {
                return ResourceManager.GetString("CheckoutLabel_Error_countryCode_NOT_NUMERIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, verifique o e-mail onde vá recever o voucher..
        /// </summary>
        internal static string CheckoutLabel_Error_email_INVALID_EMAIL {
            get {
                return ResourceManager.GetString("CheckoutLabel_Error_email_INVALID_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, verifique o e-mail onde vá recever o voucher..
        /// </summary>
        internal static string CheckoutLabel_Error_email_INVALID_LENGTH {
            get {
                return ResourceManager.GetString("CheckoutLabel_Error_email_INVALID_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, preenche o nome do cliente..
        /// </summary>
        internal static string CheckoutLabel_Error_firstName_INVALID_NAME {
            get {
                return ResourceManager.GetString("CheckoutLabel_Error_firstName_INVALID_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, verifique data de nacimiento..
        /// </summary>
        internal static string CheckoutLabel_Error_INVALID_BIRTHDAY {
            get {
                return ResourceManager.GetString("CheckoutLabel_Error_INVALID_BIRTHDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O número preenchado na corresponde á {0}.
        /// </summary>
        internal static string CheckoutLabel_Error_InvalidCardNumber {
            get {
                return ResourceManager.GetString("CheckoutLabel_Error_InvalidCardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, verifique quantidade de dígitos..
        /// </summary>
        internal static string CheckoutLabel_Error_InvalidSecurityCode {
            get {
                return ResourceManager.GetString("CheckoutLabel_Error_InvalidSecurityCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, preenche el sobrenome do cliente..
        /// </summary>
        internal static string CheckoutLabel_Error_lastName_INVALID_NAME {
            get {
                return ResourceManager.GetString("CheckoutLabel_Error_lastName_INVALID_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O endereços dos e-mails devem ser iguais..
        /// </summary>
        internal static string CheckoutLabel_Error_NotEqualEmails {
            get {
                return ResourceManager.GetString("CheckoutLabel_Error_NotEqualEmails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, verifique que número de identificação seja válido..
        /// </summary>
        internal static string CheckoutLabel_Error_ownerDocument_INVALID_DOCUMENT_NUMBER {
            get {
                return ResourceManager.GetString("CheckoutLabel_Error_ownerDocument_INVALID_DOCUMENT_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, verifique o número de identificação seja igual que do cartão de crédito. .
        /// </summary>
        internal static string CheckoutLabel_Error_ownerDocument_INVALID_LENGTH {
            get {
                return ResourceManager.GetString("CheckoutLabel_Error_ownerDocument_INVALID_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, verifique o nome do titular do cartão de crédito este preenchado. (um nome e sobrenome).
        /// </summary>
        internal static string CheckoutLabel_Error_ownerName_INVALID_CARD_OWNER_NAME {
            get {
                return ResourceManager.GetString("CheckoutLabel_Error_ownerName_INVALID_CARD_OWNER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, preenche o nome e sobrenome do dono do cartão de crédito..
        /// </summary>
        internal static string CheckoutLabel_Error_ownerName_INVALID_LENGTH {
            get {
                return ResourceManager.GetString("CheckoutLabel_Error_ownerName_INVALID_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adulto.
        /// </summary>
        internal static string CheckoutLabel_Error_PASSENGER_TYPE_ADULT {
            get {
                return ResourceManager.GetString("CheckoutLabel_Error_PASSENGER_TYPE_ADULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crianças.
        /// </summary>
        internal static string CheckoutLabel_Error_PASSENGER_TYPE_CHILD {
            get {
                return ResourceManager.GetString("CheckoutLabel_Error_PASSENGER_TYPE_CHILD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bebês.
        /// </summary>
        internal static string CheckoutLabel_Error_PASSENGER_TYPE_INFANT {
            get {
                return ResourceManager.GetString("CheckoutLabel_Error_PASSENGER_TYPE_INFANT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, preenche sobrenome do passageiro..
        /// </summary>
        internal static string CheckoutLabel_Error_passengerLast_INVALID_NAME {
            get {
                return ResourceManager.GetString("CheckoutLabel_Error_passengerLast_INVALID_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, preenche nome do passageiro..
        /// </summary>
        internal static string CheckoutLabel_Error_passengerName_INVALID_NAME {
            get {
                return ResourceManager.GetString("CheckoutLabel_Error_passengerName_INVALID_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, verifique seu número de telefone..
        /// </summary>
        internal static string CheckoutLabel_Error_phoneNumber_INVALID_LENGTH {
            get {
                return ResourceManager.GetString("CheckoutLabel_Error_phoneNumber_INVALID_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O número de telefone tem que ser números..
        /// </summary>
        internal static string CheckoutLabel_Error_phoneNumber_INVALID_PHONE_NUMBER {
            get {
                return ResourceManager.GetString("CheckoutLabel_Error_phoneNumber_INVALID_PHONE_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, verifique o número do codigo de referencia..
        /// </summary>
        internal static string CheckoutLabel_Error_voucher_INVALID_LENGTH {
            get {
                return ResourceManager.GetString("CheckoutLabel_Error_voucher_INVALID_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O codigo ingressado não existe..
        /// </summary>
        internal static string CheckoutLabel_Error_voucherDoesNotExists {
            get {
                return ResourceManager.GetString("CheckoutLabel_Error_voucherDoesNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, verifique o mes e ano de caducidade do cartao..
        /// </summary>
        internal static string CheckoutLabel_Error_YearMonthInvalid {
            get {
                return ResourceManager.GetString("CheckoutLabel_Error_YearMonthInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, leia e aceite os termos e condições..
        /// </summary>
        internal static string CheckoutLabel_Error_YouHaveToReadAndAcceptTermsAndConditions {
            get {
                return ResourceManager.GetString("CheckoutLabel_Error_YouHaveToReadAndAcceptTermsAndConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por Segurança preencher a siguente informaçao:.
        /// </summary>
        internal static string CheckoutLabel_Message_AdditionalDataNeeded {
            get {
                return ResourceManager.GetString("CheckoutLabel_Message_AdditionalDataNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e intente novamente..
        /// </summary>
        internal static string CheckoutLabel_Message_BeCorrect {
            get {
                return ResourceManager.GetString("CheckoutLabel_Message_BeCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor verifique que o cartão de crédito tenha disponibilidade ou use outro médio de pagamento..
        /// </summary>
        internal static string CheckoutLabel_Message_ChangeCreditCard {
            get {
                return ResourceManager.GetString("CheckoutLabel_Message_ChangeCreditCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dados de pagamento, .
        /// </summary>
        internal static string CheckoutLabel_Message_CheckCardData {
            get {
                return ResourceManager.GetString("CheckoutLabel_Message_CheckCardData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dados de contato, .
        /// </summary>
        internal static string CheckoutLabel_Message_CheckContact {
            get {
                return ResourceManager.GetString("CheckoutLabel_Message_CheckContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor verifique que os dados do cartão de crédito sejam correto..
        /// </summary>
        internal static string CheckoutLabel_Message_CheckCreditCardData {
            get {
                return ResourceManager.GetString("CheckoutLabel_Message_CheckCreditCardData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dados dos hóspedes, .
        /// </summary>
        internal static string CheckoutLabel_Message_CheckGuests {
            get {
                return ResourceManager.GetString("CheckoutLabel_Message_CheckGuests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor verifique a informação dada em .
        /// </summary>
        internal static string CheckoutLabel_Message_CheckItPlease {
            get {
                return ResourceManager.GetString("CheckoutLabel_Message_CheckItPlease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dados dos pasageiros, .
        /// </summary>
        internal static string CheckoutLabel_Message_CheckPassengers {
            get {
                return ResourceManager.GetString("CheckoutLabel_Message_CheckPassengers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifique os dados preenchados.
        /// </summary>
        internal static string CheckoutLabel_Message_CheckTheInformation {
            get {
                return ResourceManager.GetString("CheckoutLabel_Message_CheckTheInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu erro ao usar seu cupom de desconto, por favor tente de novo máis tarde..
        /// </summary>
        internal static string CheckoutLabel_Message_CouponNoRecoverable {
            get {
                return ResourceManager.GetString("CheckoutLabel_Message_CouponNoRecoverable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu erro processando sua solicitação, por favor tente de novo máis tarde..
        /// </summary>
        internal static string CheckoutLabel_Message_NoRecoverableError {
            get {
                return ResourceManager.GetString("CheckoutLabel_Message_NoRecoverableError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Como indicado no documento.
        /// </summary>
        internal static string CheckoutLabel_Placeholder_AsIsInDocument {
            get {
                return ResourceManager.GetString("CheckoutLabel_Placeholder_AsIsInDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome do Banco.
        /// </summary>
        internal static string CheckoutLabel_Placeholder_Bank {
            get {
                return ResourceManager.GetString("CheckoutLabel_Placeholder_Bank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ej: 6598789654984650.
        /// </summary>
        internal static string CheckoutLabel_Placeholder_CardNumber {
            get {
                return ResourceManager.GetString("CheckoutLabel_Placeholder_CardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ej: 316549879.
        /// </summary>
        internal static string CheckoutLabel_Placeholder_DocumentNumber {
            get {
                return ResourceManager.GetString("CheckoutLabel_Placeholder_DocumentNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mes (Ej: 04).
        /// </summary>
        internal static string CheckoutLabel_Placeholder_ExpirationMonth {
            get {
                return ResourceManager.GetString("CheckoutLabel_Placeholder_ExpirationMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ano (Ej: 2014).
        /// </summary>
        internal static string CheckoutLabel_Placeholder_ExpirationYear {
            get {
                return ResourceManager.GetString("CheckoutLabel_Placeholder_ExpirationYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preenche e-mail do titular.
        /// </summary>
        internal static string CheckoutLabel_Placeholder_FillEmail {
            get {
                return ResourceManager.GetString("CheckoutLabel_Placeholder_FillEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Seleccione -.
        /// </summary>
        internal static string CheckoutLabel_Placeholder_GenericSelect {
            get {
                return ResourceManager.GetString("CheckoutLabel_Placeholder_GenericSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ej: 54156423.
        /// </summary>
        internal static string CheckoutLabel_Placeholder_PhoneNumber {
            get {
                return ResourceManager.GetString("CheckoutLabel_Placeholder_PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preenche o codigo.
        /// </summary>
        internal static string CheckoutLabel_Placeholder_ReferenceCode {
            get {
                return ResourceManager.GetString("CheckoutLabel_Placeholder_ReferenceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ej: 543.
        /// </summary>
        internal static string CheckoutLabel_Placeholder_SecurityCode {
            get {
                return ResourceManager.GetString("CheckoutLabel_Placeholder_SecurityCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Li e aceito as.
        /// </summary>
        internal static string CheckoutLabel_Title_AcceptConditions {
            get {
                return ResourceManager.GetString("CheckoutLabel_Title_AcceptConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condições de compra.
        /// </summary>
        internal static string CheckoutLabel_Title_AcceptConditionsLink {
            get {
                return ResourceManager.GetString("CheckoutLabel_Title_AcceptConditionsLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        internal static string CheckoutLabel_Title_AreaCode {
            get {
                return ResourceManager.GetString("CheckoutLabel_Title_AreaCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entidade bancaria.
        /// </summary>
        internal static string CheckoutLabel_Title_Bank {
            get {
                return ResourceManager.GetString("CheckoutLabel_Title_Bank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endereço de entrega do cartão de crédito.
        /// </summary>
        internal static string CheckoutLabel_Title_Billing {
            get {
                return ResourceManager.GetString("CheckoutLabel_Title_Billing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de nascimento.
        /// </summary>
        internal static string CheckoutLabel_Title_Birthday {
            get {
                return ResourceManager.GetString("CheckoutLabel_Title_Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de cartão de crédito.
        /// </summary>
        internal static string CheckoutLabel_Title_CardNumber {
            get {
                return ResourceManager.GetString("CheckoutLabel_Title_CardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cartão.
        /// </summary>
        internal static string CheckoutLabel_Title_CardType {
            get {
                return ResourceManager.GetString("CheckoutLabel_Title_CardType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to País.
        /// </summary>
        internal static string CheckoutLabel_Title_CountryCode {
            get {
                return ResourceManager.GetString("CheckoutLabel_Title_CountryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colonia.
        /// </summary>
        internal static string CheckoutLabel_Title_County {
            get {
                return ResourceManager.GetString("CheckoutLabel_Title_County", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departamento.
        /// </summary>
        internal static string CheckoutLabel_Title_Department {
            get {
                return ResourceManager.GetString("CheckoutLabel_Title_Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informação da compra.
        /// </summary>
        internal static string CheckoutLabel_Title_Details {
            get {
                return ResourceManager.GetString("CheckoutLabel_Title_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de identidade.
        /// </summary>
        internal static string CheckoutLabel_Title_DocumentNumber {
            get {
                return ResourceManager.GetString("CheckoutLabel_Title_DocumentNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de documento.
        /// </summary>
        internal static string CheckoutLabel_Title_DocumentType {
            get {
                return ResourceManager.GetString("CheckoutLabel_Title_DocumentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail (onde vai receber seu voucher).
        /// </summary>
        internal static string CheckoutLabel_Title_Email {
            get {
                return ResourceManager.GetString("CheckoutLabel_Title_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vencimiento.
        /// </summary>
        internal static string CheckoutLabel_Title_ExpirationDate {
            get {
                return ResourceManager.GetString("CheckoutLabel_Title_ExpirationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interior.
        /// </summary>
        internal static string CheckoutLabel_Title_Intern {
            get {
                return ResourceManager.GetString("CheckoutLabel_Title_Intern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sobrenome.
        /// </summary>
        internal static string CheckoutLabel_Title_Last {
            get {
                return ResourceManager.GetString("CheckoutLabel_Title_Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        internal static string CheckoutLabel_Title_Name {
            get {
                return ResourceManager.GetString("CheckoutLabel_Title_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nacionalidade.
        /// </summary>
        internal static string CheckoutLabel_Title_Nationality {
            get {
                return ResourceManager.GetString("CheckoutLabel_Title_Nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número.
        /// </summary>
        internal static string CheckoutLabel_Title_Number {
            get {
                return ResourceManager.GetString("CheckoutLabel_Title_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exterior.
        /// </summary>
        internal static string CheckoutLabel_Title_Outer {
            get {
                return ResourceManager.GetString("CheckoutLabel_Title_Outer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sexo do titular do cartão de crédito.
        /// </summary>
        internal static string CheckoutLabel_Title_OwnerGender {
            get {
                return ResourceManager.GetString("CheckoutLabel_Title_OwnerGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome e Sobrenome do titular do cartão de crédito.
        /// </summary>
        internal static string CheckoutLabel_Title_OwnerName {
            get {
                return ResourceManager.GetString("CheckoutLabel_Title_OwnerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de identidade.
        /// </summary>
        internal static string CheckoutLabel_Title_PassDocumentNumber {
            get {
                return ResourceManager.GetString("CheckoutLabel_Title_PassDocumentNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sexo.
        /// </summary>
        internal static string CheckoutLabel_Title_PassengerGender {
            get {
                return ResourceManager.GetString("CheckoutLabel_Title_PassengerGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefone.
        /// </summary>
        internal static string CheckoutLabel_Title_Phone {
            get {
                return ResourceManager.GetString("CheckoutLabel_Title_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código Postal.
        /// </summary>
        internal static string CheckoutLabel_Title_PostalCode {
            get {
                return ResourceManager.GetString("CheckoutLabel_Title_PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código de referencia.
        /// </summary>
        internal static string CheckoutLabel_Title_ReferenceCode {
            get {
                return ResourceManager.GetString("CheckoutLabel_Title_ReferenceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirme seu e-mail.
        /// </summary>
        internal static string CheckoutLabel_Title_RepeatEmail {
            get {
                return ResourceManager.GetString("CheckoutLabel_Title_RepeatEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código de segurança.
        /// </summary>
        internal static string CheckoutLabel_Title_SecurityCode {
            get {
                return ResourceManager.GetString("CheckoutLabel_Title_SecurityCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        internal static string CheckoutLabel_Title_State {
            get {
                return ResourceManager.GetString("CheckoutLabel_Title_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calle.
        /// </summary>
        internal static string CheckoutLabel_Title_Street {
            get {
                return ResourceManager.GetString("CheckoutLabel_Title_Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decolar.com.
        /// </summary>
        internal static string CommonBrandName {
            get {
                return ResourceManager.GetString("CommonBrandName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro de conexão.
        /// </summary>
        internal static string ConnectionErrorMessage {
            get {
                return ResourceManager.GetString("ConnectionErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to adulto(s).
        /// </summary>
        internal static string FlightCheckoutDetailsAdults {
            get {
                return ResourceManager.GetString("FlightCheckoutDetailsAdults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Res. 3550 AFIP.
        /// </summary>
        internal static string FlightCheckoutDetailsAFIPRes {
            get {
                return ResourceManager.GetString("FlightCheckoutDetailsAFIPRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargos.
        /// </summary>
        internal static string FlightCheckoutDetailsCharges {
            get {
                return ResourceManager.GetString("FlightCheckoutDetailsCharges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to criança(s).
        /// </summary>
        internal static string FlightCheckoutDetailsChildren {
            get {
                return ResourceManager.GetString("FlightCheckoutDetailsChildren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bebê(s).
        /// </summary>
        internal static string FlightCheckoutDetailsInfants {
            get {
                return ResourceManager.GetString("FlightCheckoutDetailsInfants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarifa por adulto.
        /// </summary>
        internal static string FlightCheckoutDetailsPricePerAdult {
            get {
                return ResourceManager.GetString("FlightCheckoutDetailsPricePerAdult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarifa por criança.
        /// </summary>
        internal static string FlightCheckoutDetailsPricePerChild {
            get {
                return ResourceManager.GetString("FlightCheckoutDetailsPricePerChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarifa por bebê.
        /// </summary>
        internal static string FlightCheckoutDetailsPricePerInfant {
            get {
                return ResourceManager.GetString("FlightCheckoutDetailsPricePerInfant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impostos e taxas.
        /// </summary>
        internal static string FlightCheckoutDetailsTaxes {
            get {
                return ResourceManager.GetString("FlightCheckoutDetailsTaxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comprar vôo.
        /// </summary>
        internal static string FlightsCheckoutBuyFlight {
            get {
                return ResourceManager.GetString("FlightsCheckoutBuyFlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to passageiros.
        /// </summary>
        internal static string FlightsCheckoutPassengersTitle {
            get {
                return ResourceManager.GetString("FlightsCheckoutPassengersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carros.
        /// </summary>
        internal static string HomeProductCars {
            get {
                return ResourceManager.GetString("HomeProductCars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escolha carro para sua viagem..
        /// </summary>
        internal static string HomeProductCarsDescription {
            get {
                return ResourceManager.GetString("HomeProductCarsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to carros/.
        /// </summary>
        internal static string HomeProductCarsUrl {
            get {
                return ResourceManager.GetString("HomeProductCarsUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passagens.
        /// </summary>
        internal static string HomeProductFlights {
            get {
                return ResourceManager.GetString("HomeProductFlights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encontre o melhor vôo.
        /// </summary>
        internal static string HomeProductFlightsDescription {
            get {
                return ResourceManager.GetString("HomeProductFlightsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to passagens-aereas/.
        /// </summary>
        internal static string HomeProductFlightsUrl {
            get {
                return ResourceManager.GetString("HomeProductFlightsUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado do vôo.
        /// </summary>
        internal static string HomeProductFlightTracker {
            get {
                return ResourceManager.GetString("HomeProductFlightTracker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acompanhe o estado de seu vôo.
        /// </summary>
        internal static string HomeProductFlightTrackerDescription {
            get {
                return ResourceManager.GetString("HomeProductFlightTrackerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tools/flights/tracker/search/.
        /// </summary>
        internal static string HomeProductFlightTrackerUrl {
            get {
                return ResourceManager.GetString("HomeProductFlightTrackerUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel para hoje.
        /// </summary>
        internal static string HomeProductHotelForToday {
            get {
                return ResourceManager.GetString("HomeProductHotelForToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel perto para esta noite.
        /// </summary>
        internal static string HomeProductHotelForTodayDescription {
            get {
                return ResourceManager.GetString("HomeProductHotelForTodayDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hoteis/search/location/{0},{1}/{2}/{3}/2/i1.
        /// </summary>
        internal static string HomeProductHotelForTodayUrl {
            get {
                return ResourceManager.GetString("HomeProductHotelForTodayUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoteis.
        /// </summary>
        internal static string HomeProductHotels {
            get {
                return ResourceManager.GetString("HomeProductHotels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserve o quarto ideal.
        /// </summary>
        internal static string HomeProductHotelsDescription {
            get {
                return ResourceManager.GetString("HomeProductHotelsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hoteis/.
        /// </summary>
        internal static string HomeProductHotelsUrl {
            get {
                return ResourceManager.GetString("HomeProductHotelsUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meu decolar.
        /// </summary>
        internal static string HomeProductSelfservice {
            get {
                return ResourceManager.GetString("HomeProductSelfservice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veja estado de sua reservação.
        /// </summary>
        internal static string HomeProductSelfserviceDescription {
            get {
                return ResourceManager.GetString("HomeProductSelfserviceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to meudecolar/.
        /// </summary>
        internal static string HomeProductSelfserviceUrl {
            get {
                return ResourceManager.GetString("HomeProductSelfserviceUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O cartão vai ser usado só como garantia de reservação..
        /// </summary>
        internal static string HotelCheckout_CardWillBeUsedAsWarranty {
            get {
                return ResourceManager.GetString("HotelCheckout_CardWillBeUsedAsWarranty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pagamento no destino.
        /// </summary>
        internal static string HotelCheckout_PayAtDestination {
            get {
                return ResourceManager.GetString("HotelCheckout_PayAtDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 pagamento com.
        /// </summary>
        internal static string HotelCheckout_PayInOnePayment {
            get {
                return ResourceManager.GetString("HotelCheckout_PayInOnePayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pagamento de.
        /// </summary>
        internal static string HotelCheckout_PaymentOf {
            get {
                return ResourceManager.GetString("HotelCheckout_PaymentOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pagamentos de.
        /// </summary>
        internal static string HotelCheckout_PaymentsOf {
            get {
                return ResourceManager.GetString("HotelCheckout_PaymentsOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pagamentos com.
        /// </summary>
        internal static string HotelCheckout_PayWithInterest {
            get {
                return ResourceManager.GetString("HotelCheckout_PayWithInterest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pagamentos sem juros com.
        /// </summary>
        internal static string HotelCheckout_PayWithoutInterest {
            get {
                return ResourceManager.GetString("HotelCheckout_PayWithoutInterest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quarto por noite.
        /// </summary>
        internal static string HotelCheckout_PerNightRoom {
            get {
                return ResourceManager.GetString("HotelCheckout_PerNightRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opções adicionais.
        /// </summary>
        internal static string HotelCheckoutAditionalsTitle {
            get {
                return ResourceManager.GetString("HotelCheckoutAditionalsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comprar Hotel.
        /// </summary>
        internal static string HotelCheckoutBuyHotel {
            get {
                return ResourceManager.GetString("HotelCheckoutBuyHotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dados do cartão de crédito.
        /// </summary>
        internal static string HotelCheckoutCardDataTitle {
            get {
                return ResourceManager.GetString("HotelCheckoutCardDataTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to forma de pagamento.
        /// </summary>
        internal static string HotelCheckoutCardTitle {
            get {
                return ResourceManager.GetString("HotelCheckoutCardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dados do contato.
        /// </summary>
        internal static string HotelCheckoutContactTitle {
            get {
                return ResourceManager.GetString("HotelCheckoutContactTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Res. 3550 AFIP.
        /// </summary>
        internal static string HotelCheckoutDetailsAFIPRes {
            get {
                return ResourceManager.GetString("HotelCheckoutDetailsAFIPRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impostos e taxas.
        /// </summary>
        internal static string HotelCheckoutDetailsTaxes {
            get {
                return ResourceManager.GetString("HotelCheckoutDetailsTaxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to finalizar compra.
        /// </summary>
        internal static string HotelCheckoutDetailsTitle {
            get {
                return ResourceManager.GetString("HotelCheckoutDetailsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passageiros.
        /// </summary>
        internal static string HotelCheckoutPassengersTitle {
            get {
                return ResourceManager.GetString("HotelCheckoutPassengersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to forma de pagamento.
        /// </summary>
        internal static string HotelCheckoutPaymentTitle {
            get {
                return ResourceManager.GetString("HotelCheckoutPaymentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titular do quarto.
        /// </summary>
        internal static string HotelCheckoutRoomTitle {
            get {
                return ResourceManager.GetString("HotelCheckoutRoomTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to é.
        /// </summary>
        internal static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuração.
        /// </summary>
        internal static string SettingsButtonConfiguration {
            get {
                return ResourceManager.GetString("SettingsButtonConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localização.
        /// </summary>
        internal static string SettingsPage_LocationLabel {
            get {
                return ResourceManager.GetString("SettingsPage_LocationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permitir a Decolar.com usar o servico de localizacao.
        ///Decolar.com usa seus dados de localizacao para ofrecer-le hoteis perto sua locacao.
        ///Decolar.com nao comparte seus dados de localizacao..
        /// </summary>
        internal static string SettingsPage_LocationText {
            get {
                return ResourceManager.GetString("SettingsPage_LocationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuração.
        /// </summary>
        internal static string SettingsPage_SettingsLabel {
            get {
                return ResourceManager.GetString("SettingsPage_SettingsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ir para home screen.
        /// </summary>
        internal static string ThanksLabel_GoToHomePage {
            get {
                return ResourceManager.GetString("ThanksLabel_GoToHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Como continuar a compra.
        /// </summary>
        internal static string ThanksLabel_HowTheProcessContinues {
            get {
                return ResourceManager.GetString("ThanksLabel_HowTheProcessContinues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seu pagamento esta sendo processado. Quando o pagamento seja concretado vôce vai ser contatado pelo e-mail..
        /// </summary>
        internal static string ThanksLabel_ProcessDescription {
            get {
                return ResourceManager.GetString("ThanksLabel_ProcessDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informação da reservação.
        /// </summary>
        internal static string ThanksLabel_ReservationDetail {
            get {
                return ResourceManager.GetString("ThanksLabel_ReservationDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muito obrigado pela solicitação de compra!.
        /// </summary>
        internal static string ThanksLabel_ThanksForBuying {
            get {
                return ResourceManager.GetString("ThanksLabel_ThanksForBuying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seu número de solicitação de compra é.
        /// </summary>
        internal static string ThanksLabel_YourCroIdNumber {
            get {
                return ResourceManager.GetString("ThanksLabel_YourCroIdNumber", resourceCulture);
            }
        }
    }
}
