//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Despegar.LegacyCore.Resource {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Properties_PT {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Properties_PT() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Despegar.LegacyCore.Resource.Properties-PT", typeof(Properties_PT).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siguiente.
        /// </summary>
        public static string AppBarNextField {
            get {
                return ResourceManager.GetString("AppBarNextField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anterior.
        /// </summary>
        public static string AppBarPreviousField {
            get {
                return ResourceManager.GetString("AppBarPreviousField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conexión con espera de.
        /// </summary>
        public static string CheckoutLabel_Details_ConectionWith {
            get {
                return ResourceManager.GetString("CheckoutLabel_Details_ConectionWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vuelo.
        /// </summary>
        public static string CheckoutLabel_Details_Flight {
            get {
                return ResourceManager.GetString("CheckoutLabel_Details_Flight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale de.
        /// </summary>
        public static string CheckoutLabel_Details_From {
            get {
                return ResourceManager.GetString("CheckoutLabel_Details_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IDA.
        /// </summary>
        public static string CheckoutLabel_Details_IDA {
            get {
                return ResourceManager.GetString("CheckoutLabel_Details_IDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to noche(s).
        /// </summary>
        public static string CheckoutLabel_Details_Nights {
            get {
                return ResourceManager.GetString("CheckoutLabel_Details_Nights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to habitación(es).
        /// </summary>
        public static string CheckoutLabel_Details_Rooms {
            get {
                return ResourceManager.GetString("CheckoutLabel_Details_Rooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tramo.
        /// </summary>
        public static string CheckoutLabel_Details_Segment {
            get {
                return ResourceManager.GetString("CheckoutLabel_Details_Segment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to llega a.
        /// </summary>
        public static string CheckoutLabel_Details_To {
            get {
                return ResourceManager.GetString("CheckoutLabel_Details_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duración total del vuelo:.
        /// </summary>
        public static string CheckoutLabel_Details_TotalTime {
            get {
                return ResourceManager.GetString("CheckoutLabel_Details_TotalTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VUELTA.
        /// </summary>
        public static string CheckoutLabel_Details_VUELTA {
            get {
                return ResourceManager.GetString("CheckoutLabel_Details_VUELTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, ingrese el código de área del teléfono..
        /// </summary>
        public static string CheckoutLabel_Error_areaCode_INVALID_LENGTH {
            get {
                return ResourceManager.GetString("CheckoutLabel_Error_areaCode_INVALID_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, verifique que el código de área sólo contenga números..
        /// </summary>
        public static string CheckoutLabel_Error_areaCode_INVALID_PHONE_AREA_CODE {
            get {
                return ResourceManager.GetString("CheckoutLabel_Error_areaCode_INVALID_PHONE_AREA_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, ingrese el número de la tarjeta..
        /// </summary>
        public static string CheckoutLabel_Error_cardNumber_INVALID_LENGTH {
            get {
                return ResourceManager.GetString("CheckoutLabel_Error_cardNumber_INVALID_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, ingrese el código de país del teléfono..
        /// </summary>
        public static string CheckoutLabel_Error_countryCode_INVALID_LENGTH {
            get {
                return ResourceManager.GetString("CheckoutLabel_Error_countryCode_INVALID_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, verifique que el código de país sólo contenga números..
        /// </summary>
        public static string CheckoutLabel_Error_countryCode_NOT_NUMERIC {
            get {
                return ResourceManager.GetString("CheckoutLabel_Error_countryCode_NOT_NUMERIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, verifique el e-mail en donde recibirá el voucher..
        /// </summary>
        public static string CheckoutLabel_Error_email_INVALID_EMAIL {
            get {
                return ResourceManager.GetString("CheckoutLabel_Error_email_INVALID_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, verifique el e-mail en donde recibirá el voucher..
        /// </summary>
        public static string CheckoutLabel_Error_email_INVALID_LENGTH {
            get {
                return ResourceManager.GetString("CheckoutLabel_Error_email_INVALID_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, ingrese el nombre del huésped..
        /// </summary>
        public static string CheckoutLabel_Error_firstName_INVALID_NAME {
            get {
                return ResourceManager.GetString("CheckoutLabel_Error_firstName_INVALID_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, verifique la fecha de nacimiento..
        /// </summary>
        public static string CheckoutLabel_Error_INVALID_BIRTHDAY {
            get {
                return ResourceManager.GetString("CheckoutLabel_Error_INVALID_BIRTHDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El número ingresado no corresponde a una {0}.
        /// </summary>
        public static string CheckoutLabel_Error_InvalidCardNumber {
            get {
                return ResourceManager.GetString("CheckoutLabel_Error_InvalidCardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, verifique la cantidad de dígitos..
        /// </summary>
        public static string CheckoutLabel_Error_InvalidSecurityCode {
            get {
                return ResourceManager.GetString("CheckoutLabel_Error_InvalidSecurityCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, ingrese el apellido del huésped..
        /// </summary>
        public static string CheckoutLabel_Error_lastName_INVALID_NAME {
            get {
                return ResourceManager.GetString("CheckoutLabel_Error_lastName_INVALID_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Las direcciones de e-mail ingresadas en ambos campos deben ser iguales..
        /// </summary>
        public static string CheckoutLabel_Error_NotEqualEmails {
            get {
                return ResourceManager.GetString("CheckoutLabel_Error_NotEqualEmails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, verifique que el número de documento sea válido..
        /// </summary>
        public static string CheckoutLabel_Error_ownerDocument_INVALID_DOCUMENT_NUMBER {
            get {
                return ResourceManager.GetString("CheckoutLabel_Error_ownerDocument_INVALID_DOCUMENT_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, ingrese el número de documento del titular de la tarjeta..
        /// </summary>
        public static string CheckoutLabel_Error_ownerDocument_INVALID_LENGTH {
            get {
                return ResourceManager.GetString("CheckoutLabel_Error_ownerDocument_INVALID_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, verifique que el nombre del titular de tarjeta esté completo, al menos un nombre y un apellido..
        /// </summary>
        public static string CheckoutLabel_Error_ownerName_INVALID_CARD_OWNER_NAME {
            get {
                return ResourceManager.GetString("CheckoutLabel_Error_ownerName_INVALID_CARD_OWNER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, ingrese el nombre y apellido del titular de la tarjeta..
        /// </summary>
        public static string CheckoutLabel_Error_ownerName_INVALID_LENGTH {
            get {
                return ResourceManager.GetString("CheckoutLabel_Error_ownerName_INVALID_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adulto.
        /// </summary>
        public static string CheckoutLabel_Error_PASSENGER_TYPE_ADULT {
            get {
                return ResourceManager.GetString("CheckoutLabel_Error_PASSENGER_TYPE_ADULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menor.
        /// </summary>
        public static string CheckoutLabel_Error_PASSENGER_TYPE_CHILD {
            get {
                return ResourceManager.GetString("CheckoutLabel_Error_PASSENGER_TYPE_CHILD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bebe.
        /// </summary>
        public static string CheckoutLabel_Error_PASSENGER_TYPE_INFANT {
            get {
                return ResourceManager.GetString("CheckoutLabel_Error_PASSENGER_TYPE_INFANT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, ingrese el apellido del pasajero..
        /// </summary>
        public static string CheckoutLabel_Error_passengerLast_INVALID_NAME {
            get {
                return ResourceManager.GetString("CheckoutLabel_Error_passengerLast_INVALID_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, ingrese el nombre del pasajero..
        /// </summary>
        public static string CheckoutLabel_Error_passengerName_INVALID_NAME {
            get {
                return ResourceManager.GetString("CheckoutLabel_Error_passengerName_INVALID_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, verifique su número de teléfono..
        /// </summary>
        public static string CheckoutLabel_Error_phoneNumber_INVALID_LENGTH {
            get {
                return ResourceManager.GetString("CheckoutLabel_Error_phoneNumber_INVALID_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El número de teléfono sólo debe contener números..
        /// </summary>
        public static string CheckoutLabel_Error_phoneNumber_INVALID_PHONE_NUMBER {
            get {
                return ResourceManager.GetString("CheckoutLabel_Error_phoneNumber_INVALID_PHONE_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, verifique el número del código de referencia..
        /// </summary>
        public static string CheckoutLabel_Error_voucher_INVALID_LENGTH {
            get {
                return ResourceManager.GetString("CheckoutLabel_Error_voucher_INVALID_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El código ingresado no existe..
        /// </summary>
        public static string CheckoutLabel_Error_voucherDoesNotExists {
            get {
                return ResourceManager.GetString("CheckoutLabel_Error_voucherDoesNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, verifique el mes y año de vencimiento de la tarjeta..
        /// </summary>
        public static string CheckoutLabel_Error_YearMonthInvalid {
            get {
                return ResourceManager.GetString("CheckoutLabel_Error_YearMonthInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para comprar debe Leer y aceptar las condiciones de compra..
        /// </summary>
        public static string CheckoutLabel_Error_YouHaveToReadAndAcceptTermsAndConditions {
            get {
                return ResourceManager.GetString("CheckoutLabel_Error_YouHaveToReadAndAcceptTermsAndConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por seguridad complete la siguiente información:.
        /// </summary>
        public static string CheckoutLabel_Message_AdditionalDataNeeded {
            get {
                return ResourceManager.GetString("CheckoutLabel_Message_AdditionalDataNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e intente nuevamente..
        /// </summary>
        public static string CheckoutLabel_Message_BeCorrect {
            get {
                return ResourceManager.GetString("CheckoutLabel_Message_BeCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor verifique que la tarjeta disponga de fondos o intente con otro medio de pago..
        /// </summary>
        public static string CheckoutLabel_Message_ChangeCreditCard {
            get {
                return ResourceManager.GetString("CheckoutLabel_Message_ChangeCreditCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to datos de pago, .
        /// </summary>
        public static string CheckoutLabel_Message_CheckCardData {
            get {
                return ResourceManager.GetString("CheckoutLabel_Message_CheckCardData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to datos de contacto, .
        /// </summary>
        public static string CheckoutLabel_Message_CheckContact {
            get {
                return ResourceManager.GetString("CheckoutLabel_Message_CheckContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor verifique que los datos de tarjeta sean correctos e intente nuevamente..
        /// </summary>
        public static string CheckoutLabel_Message_CheckCreditCardData {
            get {
                return ResourceManager.GetString("CheckoutLabel_Message_CheckCreditCardData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to datos de los huéspedes, .
        /// </summary>
        public static string CheckoutLabel_Message_CheckGuests {
            get {
                return ResourceManager.GetString("CheckoutLabel_Message_CheckGuests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor verifique la información brindada en .
        /// </summary>
        public static string CheckoutLabel_Message_CheckItPlease {
            get {
                return ResourceManager.GetString("CheckoutLabel_Message_CheckItPlease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to datos de los pasajeros, .
        /// </summary>
        public static string CheckoutLabel_Message_CheckPassengers {
            get {
                return ResourceManager.GetString("CheckoutLabel_Message_CheckPassengers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifique los datos ingresados.
        /// </summary>
        public static string CheckoutLabel_Message_CheckTheInformation {
            get {
                return ResourceManager.GetString("CheckoutLabel_Message_CheckTheInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido un error al procesar su cupón de descuento, por favor vuelva a intentarlo mas tarde..
        /// </summary>
        public static string CheckoutLabel_Message_CouponNoRecoverable {
            get {
                return ResourceManager.GetString("CheckoutLabel_Message_CouponNoRecoverable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido un error al procesar su solicitud, por favor vuelva al listado e intentelo nuevamente..
        /// </summary>
        public static string CheckoutLabel_Message_NoRecoverableError {
            get {
                return ResourceManager.GetString("CheckoutLabel_Message_NoRecoverableError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Como figura en el documento.
        /// </summary>
        public static string CheckoutLabel_Placeholder_AsIsInDocument {
            get {
                return ResourceManager.GetString("CheckoutLabel_Placeholder_AsIsInDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre del banco.
        /// </summary>
        public static string CheckoutLabel_Placeholder_Bank {
            get {
                return ResourceManager.GetString("CheckoutLabel_Placeholder_Bank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ej: 6598789654984650.
        /// </summary>
        public static string CheckoutLabel_Placeholder_CardNumber {
            get {
                return ResourceManager.GetString("CheckoutLabel_Placeholder_CardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ej: 316549879.
        /// </summary>
        public static string CheckoutLabel_Placeholder_DocumentNumber {
            get {
                return ResourceManager.GetString("CheckoutLabel_Placeholder_DocumentNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mes (Ej: 04).
        /// </summary>
        public static string CheckoutLabel_Placeholder_ExpirationMonth {
            get {
                return ResourceManager.GetString("CheckoutLabel_Placeholder_ExpirationMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Año (Ej: 2014).
        /// </summary>
        public static string CheckoutLabel_Placeholder_ExpirationYear {
            get {
                return ResourceManager.GetString("CheckoutLabel_Placeholder_ExpirationYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese el e-mail del titular.
        /// </summary>
        public static string CheckoutLabel_Placeholder_FillEmail {
            get {
                return ResourceManager.GetString("CheckoutLabel_Placeholder_FillEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Seleccione -.
        /// </summary>
        public static string CheckoutLabel_Placeholder_GenericSelect {
            get {
                return ResourceManager.GetString("CheckoutLabel_Placeholder_GenericSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ej: 54156423.
        /// </summary>
        public static string CheckoutLabel_Placeholder_PhoneNumber {
            get {
                return ResourceManager.GetString("CheckoutLabel_Placeholder_PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese el código.
        /// </summary>
        public static string CheckoutLabel_Placeholder_ReferenceCode {
            get {
                return ResourceManager.GetString("CheckoutLabel_Placeholder_ReferenceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ej: 543.
        /// </summary>
        public static string CheckoutLabel_Placeholder_SecurityCode {
            get {
                return ResourceManager.GetString("CheckoutLabel_Placeholder_SecurityCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leí y acepto las.
        /// </summary>
        public static string CheckoutLabel_Title_AcceptConditions {
            get {
                return ResourceManager.GetString("CheckoutLabel_Title_AcceptConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to condiciones de compra..
        /// </summary>
        public static string CheckoutLabel_Title_AcceptConditionsLink {
            get {
                return ResourceManager.GetString("CheckoutLabel_Title_AcceptConditionsLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        public static string CheckoutLabel_Title_AreaCode {
            get {
                return ResourceManager.GetString("CheckoutLabel_Title_AreaCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entidad bancaria.
        /// </summary>
        public static string CheckoutLabel_Title_Bank {
            get {
                return ResourceManager.GetString("CheckoutLabel_Title_Bank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dirección de entrega del resúmen de la tarjeta.
        /// </summary>
        public static string CheckoutLabel_Title_Billing {
            get {
                return ResourceManager.GetString("CheckoutLabel_Title_Billing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de nacimiento.
        /// </summary>
        public static string CheckoutLabel_Title_Birthday {
            get {
                return ResourceManager.GetString("CheckoutLabel_Title_Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de la tarjeta.
        /// </summary>
        public static string CheckoutLabel_Title_CardNumber {
            get {
                return ResourceManager.GetString("CheckoutLabel_Title_CardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarjeta.
        /// </summary>
        public static string CheckoutLabel_Title_CardType {
            get {
                return ResourceManager.GetString("CheckoutLabel_Title_CardType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to País.
        /// </summary>
        public static string CheckoutLabel_Title_CountryCode {
            get {
                return ResourceManager.GetString("CheckoutLabel_Title_CountryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colonia.
        /// </summary>
        public static string CheckoutLabel_Title_County {
            get {
                return ResourceManager.GetString("CheckoutLabel_Title_County", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departamento.
        /// </summary>
        public static string CheckoutLabel_Title_Department {
            get {
                return ResourceManager.GetString("CheckoutLabel_Title_Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalle de la compra.
        /// </summary>
        public static string CheckoutLabel_Title_Details {
            get {
                return ResourceManager.GetString("CheckoutLabel_Title_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D.N.I del titular de la tarjeta.
        /// </summary>
        public static string CheckoutLabel_Title_DocumentNumber {
            get {
                return ResourceManager.GetString("CheckoutLabel_Title_DocumentNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de documento.
        /// </summary>
        public static string CheckoutLabel_Title_DocumentType {
            get {
                return ResourceManager.GetString("CheckoutLabel_Title_DocumentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail (donde recibirá su voucher).
        /// </summary>
        public static string CheckoutLabel_Title_Email {
            get {
                return ResourceManager.GetString("CheckoutLabel_Title_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vencimiento.
        /// </summary>
        public static string CheckoutLabel_Title_ExpirationDate {
            get {
                return ResourceManager.GetString("CheckoutLabel_Title_ExpirationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interior.
        /// </summary>
        public static string CheckoutLabel_Title_Intern {
            get {
                return ResourceManager.GetString("CheckoutLabel_Title_Intern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellido.
        /// </summary>
        public static string CheckoutLabel_Title_Last {
            get {
                return ResourceManager.GetString("CheckoutLabel_Title_Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string CheckoutLabel_Title_Name {
            get {
                return ResourceManager.GetString("CheckoutLabel_Title_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nacionalidad.
        /// </summary>
        public static string CheckoutLabel_Title_Nationality {
            get {
                return ResourceManager.GetString("CheckoutLabel_Title_Nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número.
        /// </summary>
        public static string CheckoutLabel_Title_Number {
            get {
                return ResourceManager.GetString("CheckoutLabel_Title_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exterior.
        /// </summary>
        public static string CheckoutLabel_Title_Outer {
            get {
                return ResourceManager.GetString("CheckoutLabel_Title_Outer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sexo del titular de la tarjeta.
        /// </summary>
        public static string CheckoutLabel_Title_OwnerGender {
            get {
                return ResourceManager.GetString("CheckoutLabel_Title_OwnerGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre y apellido del titular de la tarjeta.
        /// </summary>
        public static string CheckoutLabel_Title_OwnerName {
            get {
                return ResourceManager.GetString("CheckoutLabel_Title_OwnerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de documento.
        /// </summary>
        public static string CheckoutLabel_Title_PassDocumentNumber {
            get {
                return ResourceManager.GetString("CheckoutLabel_Title_PassDocumentNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sexo del pasajero.
        /// </summary>
        public static string CheckoutLabel_Title_PassengerGender {
            get {
                return ResourceManager.GetString("CheckoutLabel_Title_PassengerGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teléfono.
        /// </summary>
        public static string CheckoutLabel_Title_Phone {
            get {
                return ResourceManager.GetString("CheckoutLabel_Title_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código Postal.
        /// </summary>
        public static string CheckoutLabel_Title_PostalCode {
            get {
                return ResourceManager.GetString("CheckoutLabel_Title_PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código de referencia.
        /// </summary>
        public static string CheckoutLabel_Title_ReferenceCode {
            get {
                return ResourceManager.GetString("CheckoutLabel_Title_ReferenceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirme su e-mail.
        /// </summary>
        public static string CheckoutLabel_Title_RepeatEmail {
            get {
                return ResourceManager.GetString("CheckoutLabel_Title_RepeatEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código de seguridad.
        /// </summary>
        public static string CheckoutLabel_Title_SecurityCode {
            get {
                return ResourceManager.GetString("CheckoutLabel_Title_SecurityCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        public static string CheckoutLabel_Title_State {
            get {
                return ResourceManager.GetString("CheckoutLabel_Title_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calle.
        /// </summary>
        public static string CheckoutLabel_Title_Street {
            get {
                return ResourceManager.GetString("CheckoutLabel_Title_Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Despegar.com.
        /// </summary>
        public static string CommonBrandName {
            get {
                return ResourceManager.GetString("CommonBrandName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error de conexión..
        /// </summary>
        public static string ConnectionErrorMessage {
            get {
                return ResourceManager.GetString("ConnectionErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to adulto(s).
        /// </summary>
        public static string FlightCheckoutDetailsAdults {
            get {
                return ResourceManager.GetString("FlightCheckoutDetailsAdults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Res. 3550 AFIP.
        /// </summary>
        public static string FlightCheckoutDetailsAFIPRes {
            get {
                return ResourceManager.GetString("FlightCheckoutDetailsAFIPRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargos.
        /// </summary>
        public static string FlightCheckoutDetailsCharges {
            get {
                return ResourceManager.GetString("FlightCheckoutDetailsCharges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to menor(es).
        /// </summary>
        public static string FlightCheckoutDetailsChildren {
            get {
                return ResourceManager.GetString("FlightCheckoutDetailsChildren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bebe(s).
        /// </summary>
        public static string FlightCheckoutDetailsInfants {
            get {
                return ResourceManager.GetString("FlightCheckoutDetailsInfants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarifa por adulto.
        /// </summary>
        public static string FlightCheckoutDetailsPricePerAdult {
            get {
                return ResourceManager.GetString("FlightCheckoutDetailsPricePerAdult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarifa por menor.
        /// </summary>
        public static string FlightCheckoutDetailsPricePerChild {
            get {
                return ResourceManager.GetString("FlightCheckoutDetailsPricePerChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarifa por bebe.
        /// </summary>
        public static string FlightCheckoutDetailsPricePerInfant {
            get {
                return ResourceManager.GetString("FlightCheckoutDetailsPricePerInfant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impuestos y tasas.
        /// </summary>
        public static string FlightCheckoutDetailsTaxes {
            get {
                return ResourceManager.GetString("FlightCheckoutDetailsTaxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comprar vuelo.
        /// </summary>
        public static string FlightsCheckoutBuyFlight {
            get {
                return ResourceManager.GetString("FlightsCheckoutBuyFlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pasajeros.
        /// </summary>
        public static string FlightsCheckoutPassengersTitle {
            get {
                return ResourceManager.GetString("FlightsCheckoutPassengersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autos.
        /// </summary>
        public static string HomeProductCars {
            get {
                return ResourceManager.GetString("HomeProductCars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elija el auto para su viaje..
        /// </summary>
        public static string HomeProductCarsDescription {
            get {
                return ResourceManager.GetString("HomeProductCarsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to autos/.
        /// </summary>
        public static string HomeProductCarsUrl {
            get {
                return ResourceManager.GetString("HomeProductCarsUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vuelos.
        /// </summary>
        public static string HomeProductFlights {
            get {
                return ResourceManager.GetString("HomeProductFlights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encuentre el vuelo mas conveniente..
        /// </summary>
        public static string HomeProductFlightsDescription {
            get {
                return ResourceManager.GetString("HomeProductFlightsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to passagens-aereas/.
        /// </summary>
        public static string HomeProductFlightsUrl {
            get {
                return ResourceManager.GetString("HomeProductFlightsUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado de vuelo.
        /// </summary>
        public static string HomeProductFlightTracker {
            get {
                return ResourceManager.GetString("HomeProductFlightTracker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vea si un vuelo está en horario..
        /// </summary>
        public static string HomeProductFlightTrackerDescription {
            get {
                return ResourceManager.GetString("HomeProductFlightTrackerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tools/flights/tracker/search/.
        /// </summary>
        public static string HomeProductFlightTrackerUrl {
            get {
                return ResourceManager.GetString("HomeProductFlightTrackerUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel para hoy.
        /// </summary>
        public static string HomeProductHotelForToday {
            get {
                return ResourceManager.GetString("HomeProductHotelForToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel cercano para esta noche..
        /// </summary>
        public static string HomeProductHotelForTodayDescription {
            get {
                return ResourceManager.GetString("HomeProductHotelForTodayDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hoteles/search/location/{0},{1}/{2}/{3}/2/i1.
        /// </summary>
        public static string HomeProductHotelForTodayUrl {
            get {
                return ResourceManager.GetString("HomeProductHotelForTodayUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoteles.
        /// </summary>
        public static string HomeProductHotels {
            get {
                return ResourceManager.GetString("HomeProductHotels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserve la habitación perfecta..
        /// </summary>
        public static string HomeProductHotelsDescription {
            get {
                return ResourceManager.GetString("HomeProductHotelsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hoteis/.
        /// </summary>
        public static string HomeProductHotelsUrl {
            get {
                return ResourceManager.GetString("HomeProductHotelsUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mi Despegar.
        /// </summary>
        public static string HomeProductSelfservice {
            get {
                return ResourceManager.GetString("HomeProductSelfservice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vea el estado de su reserva..
        /// </summary>
        public static string HomeProductSelfserviceDescription {
            get {
                return ResourceManager.GetString("HomeProductSelfserviceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to midespegar/.
        /// </summary>
        public static string HomeProductSelfserviceUrl {
            get {
                return ResourceManager.GetString("HomeProductSelfserviceUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La tarjeta será utilizada como garantía de reserva..
        /// </summary>
        public static string HotelCheckout_CardWillBeUsedAsWarranty {
            get {
                return ResourceManager.GetString("HotelCheckout_CardWillBeUsedAsWarranty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pago en destino.
        /// </summary>
        public static string HotelCheckout_PayAtDestination {
            get {
                return ResourceManager.GetString("HotelCheckout_PayAtDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 pago con.
        /// </summary>
        public static string HotelCheckout_PayInOnePayment {
            get {
                return ResourceManager.GetString("HotelCheckout_PayInOnePayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pago de.
        /// </summary>
        public static string HotelCheckout_PaymentOf {
            get {
                return ResourceManager.GetString("HotelCheckout_PaymentOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pagos de.
        /// </summary>
        public static string HotelCheckout_PaymentsOf {
            get {
                return ResourceManager.GetString("HotelCheckout_PaymentsOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pagos con.
        /// </summary>
        public static string HotelCheckout_PayWithInterest {
            get {
                return ResourceManager.GetString("HotelCheckout_PayWithInterest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pagos sin interés con.
        /// </summary>
        public static string HotelCheckout_PayWithoutInterest {
            get {
                return ResourceManager.GetString("HotelCheckout_PayWithoutInterest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Habitación por noche.
        /// </summary>
        public static string HotelCheckout_PerNightRoom {
            get {
                return ResourceManager.GetString("HotelCheckout_PerNightRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opciones adicionales.
        /// </summary>
        public static string HotelCheckoutAditionalsTitle {
            get {
                return ResourceManager.GetString("HotelCheckoutAditionalsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comprar Hotel.
        /// </summary>
        public static string HotelCheckoutBuyHotel {
            get {
                return ResourceManager.GetString("HotelCheckoutBuyHotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to datos de tarjeta.
        /// </summary>
        public static string HotelCheckoutCardDataTitle {
            get {
                return ResourceManager.GetString("HotelCheckoutCardDataTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to forma de pago.
        /// </summary>
        public static string HotelCheckoutCardTitle {
            get {
                return ResourceManager.GetString("HotelCheckoutCardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to datos de contacto.
        /// </summary>
        public static string HotelCheckoutContactTitle {
            get {
                return ResourceManager.GetString("HotelCheckoutContactTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Res. 3550 AFIP.
        /// </summary>
        public static string HotelCheckoutDetailsAFIPRes {
            get {
                return ResourceManager.GetString("HotelCheckoutDetailsAFIPRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impuestos y tasas.
        /// </summary>
        public static string HotelCheckoutDetailsTaxes {
            get {
                return ResourceManager.GetString("HotelCheckoutDetailsTaxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to finalizar compra.
        /// </summary>
        public static string HotelCheckoutDetailsTitle {
            get {
                return ResourceManager.GetString("HotelCheckoutDetailsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to huéspedes.
        /// </summary>
        public static string HotelCheckoutPassengersTitle {
            get {
                return ResourceManager.GetString("HotelCheckoutPassengersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to forma de pago.
        /// </summary>
        public static string HotelCheckoutPaymentTitle {
            get {
                return ResourceManager.GetString("HotelCheckoutPaymentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titular de la habitación.
        /// </summary>
        public static string HotelCheckoutRoomTitle {
            get {
                return ResourceManager.GetString("HotelCheckoutRoomTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to es.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to configuración.
        /// </summary>
        public static string SettingsButtonConfiguration {
            get {
                return ResourceManager.GetString("SettingsButtonConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localización..
        /// </summary>
        public static string SettingsPage_LocationLabel {
            get {
                return ResourceManager.GetString("SettingsPage_LocationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permitir a Despegar.com usar el servicio de localización.
        ///Despegar.com utiliza sus datos de localización para ofrecerle hoteles cerca a su ubicación.
        ///Despegar.com no comparte sus datos de localización..
        /// </summary>
        public static string SettingsPage_LocationText {
            get {
                return ResourceManager.GetString("SettingsPage_LocationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuración.
        /// </summary>
        public static string SettingsPage_SettingsLabel {
            get {
                return ResourceManager.GetString("SettingsPage_SettingsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ir a la página de inicio.
        /// </summary>
        public static string ThanksLabel_GoToHomePage {
            get {
                return ResourceManager.GetString("ThanksLabel_GoToHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Cómo continúa el proceso de compra?.
        /// </summary>
        public static string ThanksLabel_HowTheProcessContinues {
            get {
                return ResourceManager.GetString("ThanksLabel_HowTheProcessContinues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Su pago está siendo procesado. Una vez que el pago se procese exitosamente recibirá un e-mail con la información de compra..
        /// </summary>
        public static string ThanksLabel_ProcessDescription {
            get {
                return ResourceManager.GetString("ThanksLabel_ProcessDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalle de reserva.
        /// </summary>
        public static string ThanksLabel_ReservationDetail {
            get {
                return ResourceManager.GetString("ThanksLabel_ReservationDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Muchas gracias por su solicitud de compra!.
        /// </summary>
        public static string ThanksLabel_ThanksForBuying {
            get {
                return ResourceManager.GetString("ThanksLabel_ThanksForBuying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Su número de solicitud de compra es:.
        /// </summary>
        public static string ThanksLabel_YourCroIdNumber {
            get {
                return ResourceManager.GetString("ThanksLabel_YourCroIdNumber", resourceCulture);
            }
        }
    }
}
